{% set name = "voila-vuetify" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7fa908de4c026436608afabde98abdc570aba4cf3396de48216792f3b38640c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - voila >=0.2,<0.4

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-base/index.html.j2"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-base/app.html"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-base/util.js"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-base/index.html.j2"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-base/conf.json"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-default/conf.json"  # [unix]
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/vuetify-default/app.html"  # [unix]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-base/index.html.j2"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-base/app.html"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-base/util.js"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-base/index.html.j2"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-base/conf.json"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-default/conf.json"  # [win]
    - test -f "%PREFIX%/share/jupyter/nbconvert/templates/vuetify-default/app.html"  # [win]

about:
  home: http://github.com/quantstack/voila-vuetify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Vuetify specific template for Voila

  description: |
    Vuetify specific template for Voila

extra:
  recipe-maintainers:
    - mariobuikhuizen
