{% set name = "voila-vuetify" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2378c8e207df7f4de67385bf3fb489c1a45a347271fec21c813393c00492ff67

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - voila >=0.1.11,<0.2

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/app.html"  # [unix]
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/util.js"  # [unix]
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/voila.tpl"  # [unix]
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-default/conf.json"  # [unix]
    - test -f "${PREFIX}/share/jupyter/voila/templates/vuetify-default/nbconvert_templates/app.html"  # [unix]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/app.html"  # [win]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/util.js"  # [win]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-base/nbconvert_templates/voila.tpl"  # [win]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-default/conf.json"  # [win]
    - test -f "%PREFIX%/share/jupyter/voila/templates/vuetify-default/nbconvert_templates/app.html"  # [win]

about:
  home: http://github.com/quantstack/voila-vuetify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Vuetify specific template for Voila

  description: |
    Vuetify specific template for Voila

extra:
  recipe-maintainers:
    - mariobuikhuizen
