travis:
  secure:
    BINSTAR_TOKEN: KyEUWAJRxawdh8d8mtMbddH8nJfo1wSHs5MuZ63P7qy/P0FFQTG6+Q4VPPhqeW3fTp8oiCIC8r5MVYCkGuwMge1IKbQk/O4Ys8ErKHgrFEP8uRsep7fynt/DC5td5aIWDgGuWlKL+L11cwgmEUY9wPWzLWI7y3Qm52juc3OnUBXHcWac3Rp+YnXh7a61d5pHKsZm/uwFV8b4hs5pe4Lx9SCuZ1Qnu3i2ZfEe4Mi2cnADqJ/2xfkhYo8ugei+a9QcQ7uI0uG+5qO5SYDvpFd4QX+t29pssOtODyc6uvgoiSUW3klNZOItUF+GYJFm1HeZrceFyZRAXvZKMXC92aK2YnOVX/ix9S32r82rmFcA74mtKNsjKQlZLXgJ0siOKcTNtIDpa0gf8DXIXO1WpbaiWBVE8wbck0jlzlHpJ4ntS+IhOkPzVirlRR9BPT8Tu2hW87vLj/CQ8U4HbuQ8n2JvKoJ0UikJvWtTVFDMvVyEZ+zBoRF/yCerZ1/YqDWFxdE1Ao/XorEkUWyGMzdNkkqMyhEyu57A2XOV6x/20XVFOYwwcpSdWGOtpuERbS2bebHYLMOy+mCD6CqGKhws79TY7IWnqgpPrUmKrtO32BSDrFFUAsKlrM4sq14sBNsBWnfwc8wO/lhVZSdVedRprrfoPWcssboBF1hIrssFsYguWJA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
